"""
PyLedger PDF Module - Company Branding
"""

from datetime import datetime
from typing import Optional


class CompanyInfo:
    """Company branding information for PDF reports"""

    def __init__(self,
                 name: str = '',
                 logo_path: Optional[str] = None,
                 address: str = '',
                 cr_number: str = '',
                 vat_number: str = '',
                 phone: str = '',
                 email: str = '',
                 website: str = ''):
        self.name = name
        self.logo_path = logo_path
        self.address = address
        self.cr_number = cr_number
        self.vat_number = vat_number
        self.phone = phone
        self.email = email
        self.website = website

    def header_lines(self) -> list:
        """Get header lines for document"""
        lines = [self.name]
        if self.address:
            lines.append(self.address)
        if self.cr_number:
            lines.append(f"CR: {self.cr_number}")
        if self.vat_number:
            lines.append(f"VAT: {self.vat_number}")
        return lines

    def footer_lines(self) -> list:
        """Get footer lines for document"""
        lines = []
        if self.phone:
            lines.append(f"Tel: {self.phone}")
        if self.email:
            lines.append(f"Email: {self.email}")
        if self.website:
            lines.append(self.website)
        if not lines:
            lines.append("Generated by PyLedger")
        lines.append(f"Printed: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        return lines
